version: 2

updates:
  # Backend Python dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "your-github-username"
    labels:
      - "dependencies"
      - "backend"
      - "python"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      # Ignore major version updates for stable packages
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sqlalchemy"
        update-types: ["version-update:semver-major"]
    groups:
      production-dependencies:
        patterns:
          - "fastapi"
          - "uvicorn"
          - "sqlalchemy"
          - "pydantic"
      development-dependencies:
        patterns:
          - "pytest*"
          - "black"
          - "flake8"
          - "mypy"

  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "your-github-username"
    labels:
      - "dependencies"
      - "frontend"
      - "javascript"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      # Ignore major version updates for React and Next.js
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
    groups:
      react-dependencies:
        patterns:
          - "react*"
          - "@types/react*"
      nextjs-dependencies:
        patterns:
          - "next"
          - "eslint-config-next"
      testing-dependencies:
        patterns:
          - "jest*"
          - "@testing-library/*"
          - "@playwright/test"
      ui-dependencies:
        patterns:
          - "@radix-ui/*"
          - "lucide-react"
          - "tailwind*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "your-github-username"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "your-github-username"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker)"
